name = "maile-portal"
main = "src/index.js"
compatibility_date = "2025-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
DOMAIN = "zzzz.biz.id"
APP_BASE_URL = "https://portal.zzzz.biz.id"
DEFAULT_ALIAS_LIMIT = "3"
SESSION_TTL_SECONDS = "1209600"
RESET_TTL_SECONDS = "3600"

[[d1_databases]]
binding = "DB"
database_name = "mail-portal"
database_id = "f2d38dcd-da9a-4daa-8d10-2aa5b5cd0d67"
